package com.sidorg.blog.model;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BlogAuthor")
public class BlogAuthor implements Serializable {

	private String blogAuthorId;
	private String firstName;
	private String lastName;
	private BlogSpace blogSpace;
	private String email;

	public BlogAuthor(){}
	
	@DynamoDBHashKey(attributeName = "blogAuthorId")
	@DynamoDBAutoGeneratedKey
	public String getBlogAuthorId() {
		return blogAuthorId;
	}
	
	public void setBlogAuthorId(String blogAuthorId) {
		this.blogAuthorId = blogAuthorId;
	}
	
	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBRangeKey
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	@DynamoDBAttribute
	public BlogSpace getBlogSpace() {
		return blogSpace;
	}
	
	public void setBlogSpace(BlogSpace blogSpace) {
		this.blogSpace = blogSpace;
	}
	
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "BlogAuthor [blogAuthorId=" + blogAuthorId + ", firstName="
				+ firstName + ", lastName=" + lastName + ", blogSpace="
				+ blogSpace + ", email=" + email + "]";
	}
	
}
